### ISSUE TITLE
CJ1117

### ISSUE THREAD

**Issue by dwhacks** [hallard/Omega2-IO-Power#1]
I noticed there is no BOM, yet all the parts are labeled on the board. Package sizes are still unknown, and I also have never seen a CJ1117. What is the package size? And is this regulator similar to the other 1117 variants. 

I received my v1.0 boards yesterday, lets hope they are all good!

**Comment by kasmasiini** [comment]
I have the same question about the BOM. I believe the regulator is similar to other 1117 and it looks like a SOT89 package. I would have hoped it was SOT223 as I have LD1117S33C in my inventory, but that's too large. The resistor seems to be 0805 and the cap 1206 package.

**Comment by kasmasiini** [comment]
This LDO regulator might fit and the terminal pinout is compatible: [AZ1117CR-33TRG1](http://eu.mouser.com/ProductDetail/Diodes-Incorporated/AZ1117CR-33TRG1/?qs=sGAEpiMZZMsGz1a6aV8DcGbRBi2StxQPtiFpCjf5304=)

It would still be interesting to hear from @hallard about the official BOM.

**Comment by hallard** [comment]
Sorry guys,
The regulator reference is AZ1117CR-3.3TRG1, it's like an AMS1117 in smaller footprint (SOT89)
You can find it at 

- [mouser](http://www2.mouser.com/Search/ProductDetail.aspx?R=AZ1117CR-3.3TRG1)
- [digikey](https://www.digikey.com/products/en?keywords=AZ1117CR-3.3TRG1)

Components are 0805 package for hand soldering if needed and USB connector is coming from various Ebay sellers. I remove the unused pins (just pull them out) of the USB connector, like this soldering only VCC and GND pin is easier ;-)
